### ISSUE TITLE
Runtime Error while roslaunch

### ISSUE THREAD

**Issue by pkbeen** [Kin-Zhang/OpenPCDet_ros#10]
Hello. While I study your github, i met an issue.

When roslaunch openpcdet 3d_object_detector.launch, I met this error

[ERROR] [1704847291.653335]: bad callback: <function rslidar_callback at 0x7f4c0023ba60>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/home/park/catkin_ws/src/OpenPCDet_ros/src/inference.py", line 95, in rslidar_callback
    scores, dt_box_lidar, types, pred_dict = proc_1.run(np_p, frame)
  File "/home/park/catkin_ws/src/OpenPCDet_ros/src/inference.py", line 220, in run
    pred_dicts, _ = self.net.forward(data_dict)
  File "/home/park/catkin_ws/src/OpenPCDet/pcdet/models/detectors/pv_rcnn.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/park/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/park/catkin_ws/src/OpenPCDet/pcdet/models/backbones_2d/base_bev_backbone.py", line 103, in forward
    x = torch.cat(ups, dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 225 but got size 226 for tensor number 1 in the list.

How can i solve it?

**Comment by pkbeen** [comment]
Hello. Before I solve this problem.

But I change the computer environment and met this issue.
I forgot method to solve this problem. Can you help me?

**Comment by chcchc97** [comment]
@pkbeen Hello! how can you fix this problem?

**Comment by Kin-Zhang** [comment]
Maybe these two should be linked together: https://github.com/Kin-Zhang/OpenPCDet_ros/issues/12

I didn't have this issue in demo kitti data, could you check if your OpenPCDet commit is from my fork one: https://github.com/Kin-Zhang/OpenPCDet
