### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 2. Got 226 and 225 (The offending index is 0)

### ISSUE THREAD

**Issue by chcchc97** [Kin-Zhang/OpenPCDet_ros#12]
Hello! I ran into this problem following the tutorial:
```
python3 demo.py --cfg_file cfgs/kitti_models/pv_rcnn.yaml --ckpt pv_rcnn_8369.pth --data_path 000002.bin
2024-04-27 17:32:55,082   INFO  -----------------Quick Demo of OpenPCDet-------------------------
2024-04-27 17:32:55,083   INFO  Total number of samples: 	1
2024-04-27 17:32:59,224   INFO  ==> Loading parameters from checkpoint pv_rcnn_8369.pth to CPU
2024-04-27 17:32:59,296   INFO  ==> Done (loaded 367/367)
2024-04-27 17:32:59,901   INFO  Visualized sample index: 	1
Traceback (most recent call last):
  File "demo.py", line 116, in <module>
    main()
  File "demo.py", line 102, in main
    pred_dicts, _ = model.forward(data_dict)
  File "/home/dell/chc/rohe/OpenPCDet/pcdet/models/detectors/pv_rcnn.py", line 11, in forward
    batch_dict = cur_module(batch_dict)
  File "/home/dell/app/anaconda3/envs/openmmlab/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dell/chc/rohe/OpenPCDet/pcdet/models/backbones_2d/base_bev_backbone.py", line 103, in forward
    x = torch.cat(ups, dim=1)
RuntimeError: Sizes of tensors must match except in dimension 2. Got 226 and 225 (The offending index is 0)

```

How can I fix it？

**Comment by Kin-Zhang** [comment]
I think it should be a problem to ask in OpenPCDet itself? since it is not related to ROS.

I didn't have this issue in demo kitti data, could you check if your **OpenPCDet commit** is from my fork one: https://github.com/Kin-Zhang/OpenPCDet

If so, I may need know about your one example data from you to test in my setup and debug a little bit to find the problem.
