### ISSUE TITLE
KeyError: 'model_state'

### ISSUE THREAD

**Issue by wangyakunn** [Kin-Zhang/OpenPCDet_ros#3]
Hi, Dr. Zhang
I was able to successfully run the pv_rcnn model when I was running your ROS demo, but when I was running other models such as PointPillar, this error occurred.
`Traceback (most recent call last):
  File "/home/kin/workspace/OpenPCDet_ws/src/OpenPCDet_ros/src/inference.py", line 342, in <module>
    proc_1.initialize()
  File "/home/kin/workspace/OpenPCDet_ws/src/OpenPCDet_ros/src/inference.py", line 249, in initialize
    self.read_config()
  File "/home/kin/workspace/OpenPCDet_ws/src/OpenPCDet_ros/src/inference.py", line 264, in read_config
    self.net.load_params_from_file(filename=self.model_path, logger=self.logger, to_cpu=True)
  File "/home/kin/workspace/OpenPCDet/pcdet/models/detectors/detector3d_template.py", line 368, in load_params_from_file
    model_state_disk = checkpoint['model_state']
KeyError: 'model_state'
`

**Comment by wangyakunn** [comment]
I know it was my model file not downloaded correctly.

**Comment by Kin-Zhang** [comment]
Then I closed the issue, let me know if you have other questions.
