### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by harshabolla** [Kin-Zhang/OpenPCDet_ros#7]
hii , nice work , 

i am getting following error

[ERROR] [1690993664.822849]: bad callback: <bound method Subscriber.callback of <message_filters.Subscriber object at 0xfffe947033a0>>
Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/opt/ros/noetic/lib/python3/dist-packages/message_filters/__init__.py", line 76, in callback
    self.signalMessage(msg)
  File "/opt/ros/noetic/lib/python3/dist-packages/message_filters/__init__.py", line 58, in signalMessage
    cb(*(msg + args))
  File "/opt/ros/noetic/lib/python3/dist-packages/message_filters/__init__.py", line 330, in add
    self.signalMessage(*msgs)
  File "/opt/ros/noetic/lib/python3/dist-packages/message_filters/__init__.py", line 58, in signalMessage
    cb(*(msg + args))
  File "/app/test/src/yoloandopn/src/yoloopepcdetros.py", line 489, in combined_callback
    scores, dt_box_lidar, types, pred_dict = proc_1.run(np_p, lidar_msg.header.seq)
  File "/app/test/src/yoloandopn/src/yoloopepcdetros.py", line 454, in run
    data_dict = self.demo_dataset.prepare_data(data_dict=input_dict)
  File "/app/test/src/yoloandopn/src/OpenPCDet/pcdet/datasets/dataset.py", line 180, in prepare_data
    data_dict = self.point_feature_encoder.forward(data_dict)
  File "/app/test/src/yoloandopn/src/OpenPCDet/pcdet/datasets/processor/point_feature_encoder.py", line 29, in forward
    data_dict['points'], use_lead_xyz = getattr(self, self.point_encoding_config.encoding_type)(
  File "/app/test/src/yoloandopn/src/OpenPCDet/pcdet/datasets/processor/point_feature_encoder.py", line 48, in absolute_coordinates_encoding
    assert points.shape[-1] == len(self.src_feature_list)
AssertionError

where is 00002.bin file

**Comment by Kin-Zhang** [comment]
how about trying the docker?

**Comment by harshabolla** [comment]
hii thanks for reply. i want to try without docker  and it has to deploy in edge device
